auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Forrest's blog
url: http://http://forrestpi.github.io/
feed: /atom.xml
author_info: <a href="http://http://forrestpi.github.io//">Forrest</a>
